spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      enabled: false
      server:
        #default-label: master
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///C://Users//pc//Documents//joseph-workspace//config"
        git:
          #uri: "file:///C://Users//pc//Documents//joseph-workspace//config-v2"
          uri: "https://github.com/youssefidbensalah/josephbytes-config.git"
          default-level: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

encrypt:
  key: "CE82C419913B12C85583CDDD5A573"

server:
  port: 8071